# Generated by Django 4.1.1 on 2023-05-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_usermodel_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="likes",
            field=models.JSONField(default=[{}], verbose_name="Likes"),
        ),
    ]
