# Generated by Django 4.1.1 on 2023-05-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_fact_total_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="fact_p",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.fact",
                verbose_name="Belongs to",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="description",
            field=models.CharField(default="", max_length=500, verbose_name="Comment"),
        ),
    ]
