# Generated by Django 4.1.1 on 2023-05-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="fact",
            name="total_comments",
            field=models.IntegerField(default=0, verbose_name="Total comments"),
        ),
    ]
