# Generated by Django 4.1.1 on 2023-05-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_fact_total_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="likes",
            field=models.JSONField(default={}, verbose_name="Likes"),
        ),
    ]
