# Generated by Django 4.1.1 on 2023-05-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_usermodel_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="likes",
            field=models.JSONField(
                blank=True, default={}, null=True, verbose_name="Likes"
            ),
        ),
    ]
